import java.io.*;
import java.util.*;

class Largestnumber
 {
   public static void main (String[]args)
   {

     int number1 = 50, number2 = 12;
     if (number1 == number2)
       System.out.println ("both are equal");
     else if (number1 > number2)
         System.out.println (number1 + " is Largest");

     else
         System.out.println (number2 + " is Largest");

   }
 }